import type { Category } from "./types.js";

// 20 prompts per category. Each prompt receives the city interpolated as {{city}}.
// Designed to mimic real consumer phrasing in ChatGPT + Gemini.

const TEMPLATES: Record<Category, string[]> = {
  restaurant: [
    "best restaurants in {{city}}",
    "best italian restaurant in {{city}}",
    "best mexican restaurant in {{city}}",
    "best sushi in {{city}}",
    "best pizza in {{city}}",
    "best steakhouse in {{city}}",
    "best brunch spots in {{city}}",
    "best date night restaurant in {{city}}",
    "best vegan restaurant in {{city}}",
    "best gluten free restaurant in {{city}}",
    "best family friendly restaurant in {{city}}",
    "most romantic restaurant in {{city}}",
    "best new restaurants in {{city}}",
    "best cheap eats in {{city}}",
    "best fine dining in {{city}}",
    "best seafood restaurant in {{city}}",
    "best ramen in {{city}}",
    "best taco place in {{city}}",
    "best rooftop restaurant in {{city}}",
    "where to eat in {{city}} tonight",
  ],
  dentist: [
    "best dentist in {{city}}",
    "top rated dentist in {{city}}",
    "best family dentist in {{city}}",
    "best pediatric dentist in {{city}}",
    "best cosmetic dentist in {{city}}",
    "best orthodontist in {{city}}",
    "best dentist for invisalign in {{city}}",
    "best emergency dentist in {{city}}",
    "best dental implants in {{city}}",
    "affordable dentist in {{city}}",
    "best dentist near me in {{city}}",
    "dentist accepting new patients in {{city}}",
    "best dentist for veneers in {{city}}",
    "best teeth whitening dentist in {{city}}",
    "best dentist who takes my insurance in {{city}}",
    "dentist open saturday in {{city}}",
    "best holistic dentist in {{city}}",
    "best dental office in {{city}}",
    "most gentle dentist in {{city}}",
    "highest rated dentist in {{city}}",
  ],
  lawyer: [
    "best personal injury lawyer in {{city}}",
    "best divorce lawyer in {{city}}",
    "best criminal defense attorney in {{city}}",
    "best estate planning lawyer in {{city}}",
    "best dui lawyer in {{city}}",
    "best family law attorney in {{city}}",
    "best immigration lawyer in {{city}}",
    "best employment lawyer in {{city}}",
    "best business attorney in {{city}}",
    "best real estate lawyer in {{city}}",
    "best workers compensation lawyer in {{city}}",
    "best car accident lawyer in {{city}}",
    "best bankruptcy attorney in {{city}}",
    "best contract lawyer in {{city}}",
    "best tax attorney in {{city}}",
    "best probate lawyer in {{city}}",
    "best wrongful termination lawyer in {{city}}",
    "best medical malpractice attorney in {{city}}",
    "top rated law firm in {{city}}",
    "affordable lawyer in {{city}}",
  ],
  plumber: [
    "best plumber in {{city}}",
    "emergency plumber in {{city}}",
    "24 hour plumber in {{city}}",
    "best plumbing company in {{city}}",
    "cheap plumber in {{city}}",
    "best drain cleaning service in {{city}}",
    "water heater repair in {{city}}",
    "best plumber for leak repair in {{city}}",
    "best sewer line repair in {{city}}",
    "best plumber for new construction in {{city}}",
    "best plumber for bathroom remodel in {{city}}",
    "best plumber for kitchen remodel in {{city}}",
    "tankless water heater installation in {{city}}",
    "best plumber for toilet repair in {{city}}",
    "best plumber for garbage disposal in {{city}}",
    "best plumber for sump pump in {{city}}",
    "best licensed plumber in {{city}}",
    "highly rated plumber in {{city}}",
    "best plumber for commercial in {{city}}",
    "plumber near me in {{city}}",
  ],
  spa: [
    "best spa in {{city}}",
    "best massage in {{city}}",
    "best couples massage in {{city}}",
    "best day spa in {{city}}",
    "best med spa in {{city}}",
    "best facial in {{city}}",
    "best deep tissue massage in {{city}}",
    "best swedish massage in {{city}}",
    "best prenatal massage in {{city}}",
    "best spa for bridal party in {{city}}",
    "best luxury spa in {{city}}",
    "best affordable spa in {{city}}",
    "best spa for birthday in {{city}}",
    "best waxing in {{city}}",
    "best lash extensions in {{city}}",
    "best eyebrow threading in {{city}}",
    "best spa with sauna in {{city}}",
    "best mens spa in {{city}}",
    "best spa packages in {{city}}",
    "top rated spa in {{city}}",
  ],
};

export function generatePrompts(category: Category, city: string): string[] {
  return TEMPLATES[category].map((t) => t.replaceAll("{{city}}", city));
}

export function getPromptCount(category: Category): number {
  return TEMPLATES[category].length;
}
